### ISSUE TITLE
Intermittent End-to-End Test Failures with MRD Server

### ISSUE THREAD

**Issue by apd47** [gadgetron/gadgetron#1079]
**Describe the bug**
When running integration tests, tests intermittently fail to finish due to MRD server still occupying target port

**To Reproduce**
1. Clone master
2. Open repo in devcontainer
3. Build via:
   a. cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DUSE_MKL=ON -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} ../
   b. ninja
   c. ninja install
4. Run tests via python run_tests.py --echo-log-on-failure --timeout=600 -F --stats stats.csv cases/*

**System Information:**
 - OS: Linux, Ubuntu 20.04
 - DevContainer
 - Version: master
 
**Expected behavior**
Integration tests run fully every time

**Logs/Screenshots**

Tests 1-11 passed...

Test 12 of 65: cases/external_python_bucket_example.cfg

Running Gadgetron test cases/external_python_bucket_example.cfg with:
  -- ISMRMRD_HOME    : None
  -- GADGETRON_HOME  : None
  -- TEST CASE       : cases/external_python_bucket_example.cfg
Starting MRD Storage Server on port 9113
Starting Gadgetron instance on port 9003
Converting Siemens data: data/simple_gre/meas_MiniGadgetron_GRE.dat (measurement 1) -> test/reconstruction.siemens.converted.mrd
Passing data to Gadgetron: test/reconstruction.siemens.converted.mrd -> test/reconstruction.client.output.mrd
Gadgetron processing time: 0.96 s
reconstruction.test        [OK] (Norm: 1.5e-07 [0.0001] Scale: 6.0e-08 [0.0001])
reconstruction.test        [OK] (Output headers matched reference)
Test status: Passed

Test 13 of 65: cases/external_python_buffer_example.cfg

Running Gadgetron test cases/external_python_buffer_example.cfg with:
  -- ISMRMRD_HOME    : None
  -- GADGETRON_HOME  : None
  -- TEST CASE       : cases/external_python_buffer_example.cfg
Starting MRD Storage Server on port 9113
Traceback (most recent call last):
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 728, in <module>
    sys.exit(main())
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 721, in main
    result, return_code = action_chain(test=args.test, name=args.test.stem)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 663, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 308, in handle_subprocess_errors
    return cont(**state)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 663, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 324, in clear_test_folder_action
    return cont(**state)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 663, in <lambda>
    return lambda **state: action(chain_actions(actions), **state)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 339, in start_storage_server_action
    with start_storage_server(
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 141, in start_storage_server
    wait_for_storage_server(port)
  File "/workspaces/gadgetron/test/integration/run_gadgetron_test.py", line 119, in wait_for_storage_server
    urllib.request.urlopen(f"http://localhost:{port}/healthcheck")
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/conda/envs/gadgetron/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/opt/conda/envs/gadgetron/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/opt/conda/envs/gadgetron/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/opt/conda/envs/gadgetron/lib/python3.9/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

Writing logfile test/storage.log to stdout:
{"level":"fatal","error":"listen tcp :9113: bind: address already in use","time":"2022-03-24T12:37:26.623Z"}`

**Comment by johnstairs** [comment]
I can reproduce this in a simple bash loop outside of the test scripts:

``` bash
#! /bin/bash

while :; do
  ./mrd-storage-server &

  health_check_endpoint="http://localhost:3333/healthcheck"
  for wait in {0..10}; do
    if [[ "$(curl -s -o /dev/null -m 1 -w '%{http_code}' "$health_check_endpoint")" == "200" ]]; then
      echo "Ready"
      break
    fi

    if [[ "${wait}" == "10" ]]; then
      echo "failed to connect"
      exit 1
    fi

    echo "Waiting...$wait"
    sleep 1
  done

  kill %%
done

```

Basically, the port may not be available immediately after tearing down the previous storage server instance. The storage server exits if it cannot bind to the port. The Gadgetron test scripts use a storage server process per test and I think this is what is happening.

**Comment by johnstairs** [comment]
I like the idea of keeping the storage server alive for the duration of the test suite, which also seems like a more realistic configuration. But each storage server right now gets a new temp directory created for it, so each test starts with an empty server. So this change could introduce problems. I'll give it a shot though.

**Comment by hansenms** [comment]
If we want to keep the same storage server open, we may have to introduce a session id or something that we inject to avoid that a test is a false pass because noise data is available from a previous test. I have not taken a look, but it would maybe be a bit of work.

**Comment by apd47** [comment]
Closing this issue since the bug is fixed, we can always come back to work on keeping the same storage server instance up later
